import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import header from "../../public/header.svg";
import footer from "../../public/footer.svg";
import Image from "next/image";
import profile from "../../public/profile.svg";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  blocks,
  statistic,
}: Readonly<{
  blocks: React.ReactNode;
  statistic: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen flex flex-col`}>
        <header>
          <Image src={header} alt="header" />
        </header>
        <main className="flex items-start flex-grow flex-row pt-10 px-[200px] gap-4">
          <Image src={profile} alt="profile_info" />
          <div className="gap-6 h-auto flex flex-col w-full">
            <span className="font-semibold text-[32px] leading-[44.8px] tracking-[0]">
              Сводка
            </span>
            <div className="w-full">
              {statistic}
              {blocks}
            </div>
          </div>
          {}
        </main>
        <footer>
          <Image src={footer} alt="footer" />
        </footer>
      </body>
    </html>
  );
}
